name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # This workflow will run when changes are pushed to the 'main' branch

jobs:
  web-deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest # Use the latest Ubuntu environment for the job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to check out your repository code

        - name: List files for debug
          run: ls -R

      - name: FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0 # Use the FTP Deploy Action
        with:
          # Required inputs for FTP connection:
          server: ${{ secrets.FTP_SERVER }} # Your cPanel server address (e.g., yourdomain.com or IP)
          username: ${{ secrets.FTP_USERNAME }} # Your cPanel username
          password: ${{ secrets.FTP_PASSWORD }} # Your cPanel password
          # Optional inputs:
          port: 21 # Default FTP port. Use 22 for SFTP if your cPanel supports it and you configure it.
          protocol: ftp # Use 'ftp' or 'sftp'. If using 'sftp', ensure port is 22.
          local-dir: ./web123/ # The local directory to deploy from (root of your repo)
          remote-dir: /home/chatdxyj/promptino.site # The remote directory on your cPanel (e.g., public_html, or a subfolder like public_html/my-app)
          # You can add more options like `exclude`, `dry-run`, etc.
          # For example, to exclude .git files:
          # exclude: |
          #   .git/**
          #   .github/**
          #   .env
