# .github/workflows/deploy.yml

name: Deploy to cPanel # Name of your workflow, displayed in GitHub Actions tab

on:
  push:
    branches:
      - main # This workflow will run whenever code is pushed to the 'main' branch

jobs:
  web-deploy: # Define a job named 'web-deploy'
    name: Deploy PHP Application # Display name for the job
    runs-on: ubuntu-latest # Specifies the runner environment (GitHub-hosted Ubuntu)

    steps: # List of steps to be executed in this job
    - name: Checkout code # Step 1: Give this step a descriptive name
      uses: actions/checkout@v4 # This step uses the 'checkout' action to get your repository code

    - name: Setup PHP # Step 2: Set up the PHP environment
      uses: shivammathur/setup-php@v2 # This step uses the 'setup-php' action
      with: # Parameters for the 'setup-php' action
        php-version: '8.1' # Specify your PHP version (e.g., 7.4, 8.0, 8.1, etc.)
        extensions: mbstring, pdo, json # Common PHP extensions, adjust as needed
        tools: composer # Install Composer if you plan to use it for dependencies

    # - name: Install Composer dependencies # Step 3 (Optional): Install PHP dependencies
    #   # This step is commented out by default.
    #   # If you uncomment it, ensure 'run:' is present and correctly indented.
    #   # This step uses the 'run' key to execute a shell command.
    #   run: composer install --no-dev --prefer-dist # Command to install Composer dependencies

    - name: Deploy via FTP/SFTP # Step 4: Deploy your files to the server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0 # This step uses the 'FTP-Deploy-Action'
      with: # Parameters for the 'FTP-Deploy-Action'
        server: ${{ secrets.FTP_SERVER }} # Your cPanel server IP or hostname (from GitHub Secrets)
        username: ${{ secrets.FTP_USERNAME }} # Your cPanel username (from GitHub Secrets)
        password: ${{ secrets.FTP_PASSWORD }} # Your cPanel password (from GitHub Secrets)
        # The local directory in your repository to upload from.
        # This assumes your PHP project is inside a folder named 'web123' at your repo root.
        local-dir: ./web123/
        # The remote directory on your cPanel server where your website files should go.
        # This value comes from your GitHub Secret.
        server-directory: ${{ secrets.FTP_REMOTE_PATH }}
        # Optional: Exclude files/folders you don't want to upload (e.g., .git, node_modules)
        # Uncomment and adjust this section if you want to exclude specific files.
        # exclude: |
        #   .git/
        #   .github/
        #   node_modules/
        #   .env
        #   generate_hashes.php # Definitely exclude this utility file!
        #   *.json # Be careful with this; you might want to upload data JSONs.
        #   !data/products.json # Example: include products.json if you excluded all .json
        #   !data/sales.json
        #   !data/users.json
